package com.ledger;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;

public class Block {
    private int index;
    private long timestamp;
    private ArrayList<Transaction> transactions = new ArrayList<Transaction>();
    private int nonce;
    private String hash;
    private String previousHash;
    
    public ArrayList<Transaction> getTransactions() {
        return transactions;
    }

    public int getIndex() {
        return index;
    }

    public String getHash() {
        return hash;
    }
    
    public long getTimestamp() {
        return timestamp;
    }

    public int getNonce() {
        return nonce;
    }

    public String getPreviousHash() {
        return previousHash;
    }

    public Block(int index, String previousHash, ArrayList<Transaction> transactions) {
        this.index = index;
        this.timestamp = new Date().getTime();
        this.previousHash = previousHash;
        this.transactions = transactions;
        this.nonce = 0;
        this.hash = calculateHashData();
    }

    public String calculateHashData() {
        String dataToHash = Integer.toString(index) + Long.toString(timestamp) + previousHash + Integer.toString(nonce);
        for (Transaction transaction : transactions) {
            dataToHash += transaction.toString();
        }
        try {
            // Convert the byte array generated by the SHA-256 hash function into 
            // a hexadecimal string that can be used as the data hash value for a block in a blockchain.
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(dataToHash.getBytes("UTF-8"));
            StringBuffer hexString = new StringBuffer();
            for (int i = 0; i < hash.length; i++) {
                String hex = Integer.toHexString(0xff & hash[i]);
                if (hex.length() == 1) hexString.append('0');
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException | UnsupportedEncodingException e) {
            e.printStackTrace();
            return null;
        }
    }

    public void mineBlock(int difficulty) {
        String target = new String(new char[difficulty]).replace('\0', '0');
        while (!hash.substring(0, difficulty).equals(target)) {
            nonce++;
            hash = calculateHashData();
        }
    }

    public boolean addTransaction(Transaction transaction) {
        if (transaction == null) return false;
        if ((previousHash != "0")) {
            if ((transaction.processTransaction() != true)) {
                return false;
            }
        }
        transactions.add(transaction);
        return true;
    }
}
