package com.ledger.blockchain;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;

import com.ledger.consensus.ProofOfWork;
import com.ledger.transaction.Transaction;

public class Block {
    private int index;
    private long timestamp;
    private ArrayList<Transaction> transactions = new ArrayList<Transaction>();
    private int nonce;
    private String hash;
    private String previousHash;
    
    public ArrayList<Transaction> getTransactions() {
        return transactions;
    }

    public int getIndex() {
        return index;
    }

    public String getHash() {
        return hash;
    }
    
    public long getTimestamp() {
        return timestamp;
    }

    public int getNonce() {
        return nonce;
    }

    public String getPreviousHash() {
        return previousHash;
    }

    public void setNonce(int nonce) {
        this.nonce = nonce;
    }

    public void setHash(String calculatedHashData) {
        this.hash = calculatedHashData;
    }

    // Overriding toString() method of String class
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(" Index: ").append(index).append("\n");
        sb.append(" Timestamp: ").append(timestamp).append("\n");
        sb.append(" Previous Hash: ").append(previousHash).append("\n");
        sb.append(" Nonce: ").append(nonce).append("\n");
        sb.append(" Hash: ").append(hash).append("\n");
        sb.append(" Transactions: [\n");
        for (Transaction transaction : transactions) {
            sb.append(transaction.toString()).append("\n");
        }
        sb.append(" ]\n");
        return sb.toString();
    }

    public Block(int index, String previousHash, ArrayList<Transaction> transactions) {
        this.index = index;
        this.timestamp = new Date().getTime();
        this.previousHash = previousHash;
        this.transactions = transactions;
        this.nonce = 0;
    }

    public String calculateHashData() {
        String dataToHash = Integer.toString(index) + Long.toString(timestamp) + previousHash + Integer.toString(nonce);
        for (Transaction transaction : transactions) {
            dataToHash += transaction.toString();
        }
        try {
            // Convert the byte array generated by the SHA-256 hash function into 
            // a hexadecimal string that can be used as the data hash value for a block in a blockchain.
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(dataToHash.getBytes("UTF-8"));
            StringBuffer hexString = new StringBuffer();
            for (int i = 0; i < hash.length; i++) {
                String hex = Integer.toHexString(0xff & hash[i]);
                if (hex.length() == 1) hexString.append('0');
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException | UnsupportedEncodingException e) {
            e.printStackTrace();
            return null;
        }
    }

    
    public void mineBlock(int consensus, int difficulty) {
        switch (consensus) {
            case 1: // Proof-of-Work (PoW)
                ProofOfWork.mineBlock(this, difficulty);
                break;
        
            default: // Make default case Proof-of-Work
                ProofOfWork.mineBlock(this, difficulty);
                break;
        }
    }

    // public boolean addTransaction(Transaction transaction) {
    //     if (transaction == null) return false;
    //     if ((previousHash != "0")) {
    //         if ((transaction.processTransaction() != true)) {
    //             return false;
    //         }
    //     }
    //     transactions.add(transaction);
    //     return true;
    // }

   
}
